config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                              Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
#            user_password POST   /users/password(.:format)                devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)            devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
#                          PATCH  /users/password(.:format)                devise/passwords#update
#                          PUT    /users/password(.:format)                devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PATCH  /users(.:format)                         devise/registrations#update
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#     unauthenticated_root GET    /                                        home#unregistered
#  lab_customer_home_index GET    /lab/customer/home(.:format)             lab/customer/home#index
#    lab_customer_products GET    /lab/customer/products(.:format)         lab/customer/products#index
#     lab_customer_product GET    /lab/customer/products/:id(.:format)     lab/customer/products#show
#     lab_admin_home_index GET    /lab/admin/home(.:format)                lab/admin/home#index
#      lab_admin_customers GET    /lab/admin/customers(.:format)           lab/admin/customers#index
#                          POST   /lab/admin/customers(.:format)           lab/admin/customers#create
#   new_lab_admin_customer GET    /lab/admin/customers/new(.:format)       lab/admin/customers#new
#  edit_lab_admin_customer GET    /lab/admin/customers/:id/edit(.:format)  lab/admin/customers#edit
#       lab_admin_customer GET    /lab/admin/customers/:id(.:format)       lab/admin/customers#show
#                          PATCH  /lab/admin/customers/:id(.:format)       lab/admin/customers#update
#                          PUT    /lab/admin/customers/:id(.:format)       lab/admin/customers#update
#                          DELETE /lab/admin/customers/:id(.:format)       lab/admin/customers#destroy
#     lab_admin_categories GET    /lab/admin/categories(.:format)          lab/admin/categories#index
#                          POST   /lab/admin/categories(.:format)          lab/admin/categories#create
#   new_lab_admin_category GET    /lab/admin/categories/new(.:format)      lab/admin/categories#new
#  edit_lab_admin_category GET    /lab/admin/categories/:id/edit(.:format) lab/admin/categories#edit
#       lab_admin_category GET    /lab/admin/categories/:id(.:format)      lab/admin/categories#show
#                          PATCH  /lab/admin/categories/:id(.:format)      lab/admin/categories#update
#                          PUT    /lab/admin/categories/:id(.:format)      lab/admin/categories#update
#                          DELETE /lab/admin/categories/:id(.:format)      lab/admin/categories#destroy
#       lab_admin_products GET    /lab/admin/products(.:format)            lab/admin/products#index
#                          POST   /lab/admin/products(.:format)            lab/admin/products#create
#    new_lab_admin_product GET    /lab/admin/products/new(.:format)        lab/admin/products#new
#   edit_lab_admin_product GET    /lab/admin/products/:id/edit(.:format)   lab/admin/products#edit
#        lab_admin_product GET    /lab/admin/products/:id(.:format)        lab/admin/products#show
#                          PATCH  /lab/admin/products/:id(.:format)        lab/admin/products#update
#                          PUT    /lab/admin/products/:id(.:format)        lab/admin/products#update
#                          DELETE /lab/admin/products/:id(.:format)        lab/admin/products#destroy
#                 products GET    /products(.:format)                      products#index
#                  product GET    /products/:id(.:format)                  products#show
# 

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'home#unregistered', as: :unauthenticated_root
    end
  end

  namespace :lab do
    namespace :customer do
      resources :home, only: [:index]
      resources :products, only: [:index, :show]
    end

    namespace :admin do
      resources :home, only: [:index]

      resources :categories
      resources :products
    end
  end

  resources :products, only: [:index, :show]
  root 'home#unregistered'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  active      :boolean          default(TRUE), not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :products
end

app/controllers/lab/admin/categories_controller.rb
module Lab
  module Admin
    class CategoriesController < ApplicationController
      before_action :valid_admin, :authenticate_user!
      before_action :set_category, only: [:show, :edit, :update, :destroy]

      # GET /categories
      # GET /categories.json
      def index
        @categories = Category.all
      end

      # GET /categories/1
      # GET /categories/1.json
      def show; end

      # GET /categories/new
      def new
        @category = Category.new
      end

      # GET /categories/1/edit
      def edit; end

      # POST /categories
      # POST /categories.json
      def create
        @category = Category.new(category_params)

        respond_to do |format|
          if @category.save
            format.html { redirect_to [:lab_admin, @category], notice: 'Category was successfully created.' }
            format.json { render :show, status: :created, location: [:lab_admin, @category] }
          else
            format.html { render :new }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /categories/1
      # PATCH/PUT /categories/1.json
      def update
        respond_to do |format|
          if @category.update(category_params)
            format.html { redirect_to [:lab_admin, @category], notice: 'Category was successfully updated.' }
            format.json { render :show, status: :ok, location: [:lab_admin, @category] }
          else
            format.html { render :edit }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /categories/1
      # DELETE /categories/1.json
      def destroy
        @category.destroy
        respond_to do |format|
          format.html { redirect_to lab_admin_categories_url, notice: 'Category was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def category_params
        params.require(:category).permit(
          :name,
          :active,
          :description
        )
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/lab/admin/categories/_form.html.erb
<%= simple_form_for [:lab_admin, @category] do |f| %>
  <% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :name %>
  <%= f.label :active %>
  <%= f.collection_radio_buttons :active, [[true, 'Yes'] ,[false, 'No']], :first, :last %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/lab/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', [:lab_admin, @category] %> |
<%= link_to 'Back', lab_admin_categories_path %>

app/views/lab/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.active %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', [:lab_admin, category] %></td>
        <td><%= link_to 'Edit', edit_lab_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', [:lab_admin, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_lab_admin_category_path %>

app/views/lab/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', lab_admin_categories_path %>

app/views/lab/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @category.active %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_lab_admin_category_path(@category) %> |
<%= link_to 'Back', lab_admin_categories_path %>